image: amazon/aws-cli

pipelines:
  default:
    - step:
        oidc: true
        script:
          
          - export AWS_WEB_IDENTITY_TOKEN_FILE=$(pwd)/web-identity-token
          - echo $BITBUCKET_STEP_OIDC_TOKEN > $(pwd)/web-identity-token
          - echo $AWS_REGION
          - echo AWS_ROLE_ARN
          
          # Install p7zip using yum
          - echo "Installing zip..."
          - if ! command -v zip &> /dev/null; then yum install -y zip; fi
          
          # Run deploy.sh script for deployment
          - chmod +x deploy.sh
          - ./deploy.sh  # This runs the deploy script, which handles all AWS deployment tasks

    - step:
        name: Run Cypress Tests
        image: cypress/included:13.15.2
        caches:
          - node
        script:
          # install necessary dependencies 
          - npm ci 
          - npm install mochawesome 

        # Run Cypress tests
          - npx cypress run --reporter mochawesome

        artifacts:
          - mochawesome-report/**
          - cypress/screenshots/**
