name: Deploy Cloud Resume Challenge

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  # Job 1: Deploy ACM Certificate
  deploy_certificate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN}}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Make scripts executable
        run: chmod +x scripts/*.sh

      - name: Deploy ACM Certificate
        id: deploy_acm_certificate
        run: |
          ./scripts/deploy_acm_certificate.sh
        env:
          DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
          CERTIFICATE_REGION: ${{ secrets.CERTIFICATE_REGION }}
          NEW_CERTIFICATE_STACK_NAME: ${{ secrets.NEW_CERTIFICATE_STACK_NAME }}

  # Job 2: Deploy CloudFormation stacks (depends on the first job)
  deploy_stack:
    runs-on: ubuntu-latest
    needs: deploy_certificate  # This job will only run after deploy_certificate
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN}}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Make scripts executable
        run: chmod +x scripts/*.sh

      - name: Build and upload Lambda
        run: ./scripts/build_lambda.sh

      - name: Deploy CloudFormation stacks
        run: ./scripts/deploy_cloudformation_stacks.sh
        env:
          DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
          CERTIFICATE_REGION: ${{ secrets.CERTIFICATE_REGION }}
          NEW_CERTIFICATE_STACK_NAME: ${{ secrets.NEW_CERTIFICATE_STACK_NAME }}
    

  # Job 3: Update frontend (depends on the second job)
  update_frontend:
    runs-on: ubuntu-latest
    needs: deploy_stack  # This job will only run after deploy_stack
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make scripts executable
        run: chmod +x scripts/*.sh

      - name: Update frontend
        run: ./scripts/update_frontend.sh
        env:
          DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
          
